// Generated by https://quicktype.io

export interface ICategoriesReponse {
    data: ISimpleCategory[];
}

export interface ISimpleCategory {
    id:          string;
    name:        string;
    slug:        string;
    image:       string;
    description: string;
}
