// Generated by https://quicktype.io

export interface IFullCategory {
    id:          string;
    slug:        string;
    name:        string;
    image:       string;
    description: string;
    created_at:  string;
    updated_at:  string;
    products:    Product[];
}

interface Product {
    id:          string;
    name:        string;
    slug:        string;
    stock:       number;
    description: string;
    category_id: string;
    created_at:  string;
    updated_at:  string;
    price:       number;
}
